In [1]:
#take note about numpy package
import numpy as np

#use fix, ceil, floor, trunc, rint all return float type
#np.rint(), round to nearest int
number = 2.6
print(np.rint(number))
print(type(np.rint(number)))
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
print(np.rint(a))
print(type(np.rint(a)))

#np.fix() round to nearest 0
print('np.fix')
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
print(np.fix(a))
#trunc round to nea
print('np.trunc: ')
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
print(np.trunc(a))
print('np.floor: ')
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
print(np.floor(a))
print('np.ceil: ')
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
print(np.ceil(a))

3.0
<class 'numpy.float64'>
[-2. -2. -0.  0.  2.  2.  2.]
<class 'numpy.ndarray'>
np.fix
[-1. -1. -0.  0.  1.  1.  2.]
np.trunc: 
[-1. -1. -0.  0.  1.  1.  2.]
np.floor: 
[-2. -2. -1.  0.  1.  1.  2.]
np.ceil: 
[-1. -1. -0.  1.  2.  2.  2.]


In [2]:
 total_result = 392
 number_item_each_page = 30
 num_page = np.ceil(total_result/number_item_each_page)
 print(num_page)
 print(int(num_page))

14.0
14
